project:
  type: website

website:
  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [edit, issue]
  title: "Semillero Computer Vision"
  navbar:
    logo: "logo.png"
    background: primary

    left:
      - text: Inicio
        href: index.qmd
      - about.qmd

    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://code.com
          - text: Report a Bug
            url:  https://bugs.com'

  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd
    
      - section: "Layout"
        contents:
          - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



